const CHARACTERS=["拉蒙娜","环行·拉蒙娜","朵尔","熔毁·朵尔","奥吉尔","萝坦","蚀灭·萝坦","莱克","「24」","诺缔拉","宁菲亚","潘狄娅","莉莉","艾尔瓦","珈伦","哈姆林","塔薇","凯蒂古拉","茉夏","图鲁","神王·图鲁","墨菲","诞妄·墨菲","法洛思","凯刻斯","奥瑞塔","戈利亚","弥利亚姆","珊","希莱斯特","克珀珊特","莫丝","庞托斯","泰旖丝","萨尔瓦多","艾继丝","索蕾尔","希洛","血链·希洛","阿格里帕","尤乌哈希","雷娅","菲茵特","杜勒赛因","卡拉布","皮克曼","徐","沙耶","莉兹","达芙黛尔","汀克特","旺达","温柯尔","奥尔拉","詹金","艾瑞卡","卡茜亚","阿拉克涅","卡斯托尔","克莱门汀","波吕克斯"];
const FALLBACK_SKILLS={
  "莱克":[{name:"肆意豪赌",levels:[60,72,84,96,108,120],desc:"对所有敌人造成 [攻击力*60%→120%] 点伤害；同时根据抽牌数量获得力量。"}],
  "神王·图鲁":[{name:"打击",levels:[10,12,14,16,18],desc:"造成 [攻击力*10%→18%] 点伤害，并获得狂气。"}],
  "血链·希洛":[{name:"缚身锁链",levels:[100],desc:"Lv1：造成 [攻击力*100%] 点伤害，并带有出血/护盾相关效果。"}],
  "萝坦":[{name:"混沌之兽",levels:[40],desc:"Lv1：对所有敌人造成 [攻击力*40%] 点伤害；每打出1张「打击」使该技能额外增加 [攻击力*8%]。"}],
  "艾继丝":[{name:"万古之眸",levels:[75],desc:"Lv1：对所有敌人造成 [攻击力*75%] 点伤害并施加易伤；重复释放会提高基础伤害。"}]
};
const FALLBACK_FATES={"陨日":{power:14.4,text:"主属性：伤害强效 14.4%。特性包含基础伤害 / 中毒 / 反击相关强化，条件部分不自动套用。"},"虔诚的伟力":{critDamage:21.6,text:"0阶主属性：暴击伤害 21.6%。更高正位阶数会继续提高，页面同步成功时以实时页面为准。"}};
const FALLBACK_CONTRACTS={"四月礼赞":{three:{critDamage:7.2},six:{critRate:35,critDamage:35},text:"3件套：暴击伤害 +7.2%。6件套：回合开始时，若敌人总生命 >75%，装备者临时暴击率和暴击伤害 +35%。"},"再衍化":{three:{},six:{},text:"3件套：狂气回充等级 +2.4；6件套为狂气相关效果，不直接改本页伤害乘区。"}};
const SHORT_QUOTES={"希洛":"目标在哪？","血链·希洛":"仇恨的火焰熊熊燃烧。","达芙黛尔":"让我听听看您的需求吧。","杜勒赛因":"非常感谢你的热情，我很荣幸。","莫丝":"我！莫丝！你好！"};
const LEVELS=["大吉","吉","小吉","平","小凶"],GOOD=["刷同调率","把爆发留给关键回合","补齐角色档案","整理命轮与密契","打一次高分调查","给主力重新核对乘区","带喜欢的角色上场","看一段角色故事"],BAD=["只看面板不看乘区","忘记核对暴击率","把不同增伤直接相加","无脑追单一词条","低血量时贪输出","不看技能描述就抄作业","连续失败还不换思路"],STATS=["伤害强效","暴击伤害","最终伤害","易伤","技能倍率","攻击力"],KEYWORDS=["克制","观察","蓄力","谨慎","果断","耐心","交换","复仇","好奇","记忆","回响","深潜"],FORTUNES=["今天更适合把资源集中到一个明确目标上。先确认核心乘区，再决定是否继续堆叠同类增益。","今天的收益来自细节：多看一眼技能描述，多核对一次触发条件，通常比单纯堆面板更有效。","适合尝试新的队伍搭配，但最好保留一套熟悉阵容做基准，比较前后变化会更清楚。","今天适合做减法。删掉不稳定的触发条件，把输出链条压缩到最容易复现的几步。","把一次失败当成数据点。记录造成差异的 Buff、目标状态和暴击情况，下一次会更接近真实公式。"];

let resultMode="expected",rerollSalt=0,currentSkills=[],fateAuto={},contractAuto={},charRequestId=0;
const $=id=>document.getElementById(id),num=id=>Number($(id).value)||0,fmt=v=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(Number.isFinite(v)?v:0),clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const clean=s=>(s||"").replace(/\s+/g," ").trim();
function wikiUrl(name){return `https://morimens.huijiwiki.com/wiki/${encodeURIComponent(name)}`}
async function fetchWikiHTML(page){const url=`https://morimens.huijiwiki.com/api.php?action=parse&format=json&origin=*&prop=text&page=${encodeURIComponent(page)}`;const c=new AbortController();const t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{signal:c.signal,cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();return j?.parse?.text?.["*"]||""}finally{clearTimeout(t)}}
function docFromHTML(html){return new DOMParser().parseFromString(html,"text/html")}
function setSync(kind,msg,state=""){if(kind==="char"){$("charSyncStatus").textContent=msg;$(`charSyncDot`).className=`syncDot ${state}`;$(`charSyncText`).textContent=state==="ok"?"实时数据已载入":state==="warn"?"使用 fallback":"同步中"}}
function extractAttackPercents(text){const out=[];const re=/攻击力\s*[×xX*]\s*([0-9]+(?:\.[0-9]+)?)\s*%/g;let m;while((m=re.exec(text)))out.push(Number(m[1]));return out}
function extractNamedPercents(text){const obj={};const map=[["伤害强效","power"],["暴击率","critRate"],["暴击伤害","critDamage"],["基础伤害","base"],["最终伤害","final"],["易伤","vulnerability"]];for(const [label,key] of map){const re=new RegExp(`${label}[^0-9+\\-]{0,18}[+＋]?\\s*([0-9]+(?:\\.[0-9]+)?)\\s*%`);const m=text.match(re);if(m)obj[key]=Number(m[1])}return obj}
function extractCharacterSkills(html){const doc=docFromHTML(html),skills=[];const seen=new Set();for(const table of doc.querySelectorAll("table")){const rows=[...table.querySelectorAll("tr")];if(rows.length<2)continue;const all=clean(table.textContent);if(!/攻击力\s*[×xX*]/.test(all))continue;let skillName="";const first=rows[0];if(first){const cells=[...first.querySelectorAll("th,td")].map(x=>clean(x.textContent)).filter(Boolean);skillName=cells.find(x=>!/等级|描述|故事|消耗算力|基础狂气/.test(x)&&x.length<=30)||""}if(!skillName){let p=table.previousElementSibling;for(let i=0;p&&i<4;i++,p=p.previousElementSibling){const t=clean(p.textContent);if(t&&t.length<40&&!/技能|Skills/.test(t)){skillName=t;break}}}if(!skillName)skillName=`技能 ${skills.length+1}`;const levels=[];const descs=[];for(const row of rows){const cells=[...row.querySelectorAll("th,td")];if(cells.length<2)continue;const levelText=clean(cells[0].textContent),desc=clean(cells[1].textContent);if(!/^\d+$/.test(levelText)||!/攻击力\s*[×xX*]/.test(desc))continue;const ps=extractAttackPercents(desc);if(ps.length){levels[Number(levelText)-1]=ps[0];descs[Number(levelText)-1]=desc}}const vals=levels.filter(v=>Number.isFinite(v));if(vals.length){const key=`${skillName}:${vals.join(",")}`;if(!seen.has(key)){seen.add(key);skills.push({name:skillName,levels,descs,desc:descs.find(Boolean)||all.slice(0,260)})}}}return skills}
function populateCharacters(){for(const name of CHARACTERS){const o=document.createElement("option");o.value=name;o.textContent=name;$(`charSelect`).appendChild(o)}$(`charSelect`).value="莱克"}
function fillSkillUI(skills,source){currentSkills=skills;$(`skillSelect`).innerHTML="";if(!skills.length){$(`skillSelect`).innerHTML='<option value="">未解析到直接攻击技能</option>';$(`skillLevel`).innerHTML='<option value="1">1</option>';$(`skillDesc`).textContent="该角色页面没有解析到 [攻击力*XX%] 形式的直接伤害技能；可展开高级字段手动填写倍率。";return}skills.forEach((s,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=s.name;$(`skillSelect`).appendChild(o)});$(`skillSelect`).value="0";updateSkillLevels();$(`skillDesc`).innerHTML=`<strong>${source}</strong> · ${escapeHTML(skills[0].desc||"")}`}
function updateSkillLevels(){const s=currentSkills[Number($(`skillSelect`).value)||0];$(`skillLevel`).innerHTML="";if(!s)return;for(let i=0;i<s.levels.length;i++){if(!Number.isFinite(s.levels[i]))continue;const o=document.createElement("option");o.value=String(i);o.textContent=`Lv.${i+1} · ${s.levels[i]}%`;$(`skillLevel`).appendChild(o)}if(!$(`skillLevel`).options.length){$(`skillLevel`).innerHTML='<option value="0">Lv.1</option>'}applySelectedSkill()}
function applySelectedSkill(){const s=currentSkills[Number($(`skillSelect`).value)||0];if(!s)return;const li=Number($(`skillLevel`).value)||0;const coef=s.levels[li];if(Number.isFinite(coef))$(`skillCoef`).value=coef;const desc=s.descs?.[li]||s.desc||"";$(`skillDesc`).innerHTML=`<strong>${escapeHTML(s.name)}</strong> · ${escapeHTML(desc)}`;calculate()}
async function loadCharacter(){const name=$(`charSelect`).value,id=++charRequestId;setSync("char",`正在读取 ${name}…`,"");fillSkillUI([],"加载中");try{const html=await fetchWikiHTML(name);if(id!==charRequestId)return;const skills=extractCharacterSkills(html);if(skills.length){fillSkillUI(skills,"中文维基实时技能表");setSync("char",`已解析 ${skills.length} 个含直接攻击倍率的技能`,`ok`)}else throw new Error("未解析到倍率")}catch(e){if(id!==charRequestId)return;const fb=FALLBACK_SKILLS[name]||[];fillSkillUI(fb,fb.length?"内置已核对 fallback":"无 fallback");setSync("char",fb.length?`实时同步失败，使用 ${name} 内置样例`:`实时同步失败；该角色请手填技能倍率`,`warn`)}calculate()}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function firstMainStat(text){const labels=[["伤害强效","power"],["暴击率","critRate"],["暴击伤害","critDamage"]];for(const [label,key] of labels){const m=text.match(new RegExp(`${label}\\s*([0-9]+(?:\\.[0-9]+)?)\\s*%`));if(m)return {[key]:Number(m[1]),label,value:Number(m[1])}}return {}}
async function loadFate(){const name=$(`fateSelect`).value;fateAuto={};if(!name){$(`fateDesc`).textContent="未装备命轮。";calculate();return}try{const html=await fetchWikiHTML(name),text=clean(docFromHTML(html).body.textContent),stat=firstMainStat(text);fateAuto=stat;$(`fateDesc`).innerHTML=`<strong>实时读取：</strong>${escapeHTML(text.slice(0,520))}`;}catch(e){fateAuto=FALLBACK_FATES[name]||{};$(`fateDesc`).innerHTML=fateAuto.text?`<strong>内置 fallback：</strong>${escapeHTML(fateAuto.text)}`:"同步失败，未自动计入任何命轮数值。"}calculate()}
function parseContract(text){const result={three:{},six:{},text};const m3=text.match(/3件套[：:]?(.{0,220})/),m6=text.match(/6件套[：:]?(.{0,360})/);if(m3)result.three=extractNamedPercents(m3[1]);if(m6)result.six=extractNamedPercents(m6[1]);return result}
async function loadContract(){const name=$(`contractSelect`).value;contractAuto={};if(!name){$(`contractDesc`).textContent="未装备密契。";calculate();return}try{const html=await fetchWikiHTML(name),text=clean(docFromHTML(html).body.textContent);contractAuto=parseContract(text);$(`contractDesc`).innerHTML=`<strong>实时读取：</strong>${escapeHTML(text.slice(0,650))}`;}catch(e){contractAuto=FALLBACK_CONTRACTS[name]||{};$(`contractDesc`).innerHTML=contractAuto.text?`<strong>内置 fallback：</strong>${escapeHTML(contractAuto.text)}`:"同步失败，未自动计入任何密契数值。"}calculate()}
async function loadCategoryOptions(category,selectId,keep=[]){try{let cmcontinue="",names=[];do{const u=new URL("https://morimens.huijiwiki.com/api.php");u.searchParams.set("action","query");u.searchParams.set("format","json");u.searchParams.set("origin","*");u.searchParams.set("list","categorymembers");u.searchParams.set("cmtitle",`Category:${category}`);u.searchParams.set("cmlimit","500");u.searchParams.set("cmnamespace","0");if(cmcontinue)u.searchParams.set("cmcontinue",cmcontinue);const r=await fetch(u);const j=await r.json();names.push(...(j.query?.categorymembers||[]).map(x=>x.title));cmcontinue=j.continue?.cmcontinue||""}while(cmcontinue);const sel=$(selectId),current=sel.value,all=[...new Set([...keep,...names])].filter(n=>n&&!/预设|搜索/.test(n)).sort((a,b)=>a.localeCompare(b,"zh-CN"));sel.innerHTML='<option value="">无</option>'+all.map(n=>`<option>${escapeHTML(n)}</option>`).join("");if(all.includes(current))sel.value=current}catch(e){}}
function autoModifiers(){const m={power:0,critRate:0,critDamage:0,vulnerability:0,final:0,base:0,strength:0,damageMult:1,labels:[]};const add=(k,v,label)=>{if(!Number.isFinite(v)||!v)return;m[k]=(m[k]||0)+v;m.labels.push(`${label} ${v>0?"+":""}${v}${k==="strength"?"":"%"}`)};add("power",fateAuto.power||0,"命轮·伤害强效");add("critRate",fateAuto.critRate||0,"命轮·暴击率");add("critDamage",fateAuto.critDamage||0,"命轮·暴击伤害");const pcs=Number($(`contractPieces`).value)||0;if(pcs>=3){for(const k of ["power","critRate","critDamage","base","final","vulnerability"])add(k,contractAuto.three?.[k]||0,`密契3件·${k}`)}if(pcs>=6&&$(`contractConditional`).checked){for(const k of ["power","critRate","critDamage","base","final","vulnerability"])add(k,contractAuto.six?.[k]||0,`密契6件·${k}`)}if($(`buffVuln`).checked)add("vulnerability",50,"易伤");if($(`buffWeak`).checked){m.damageMult*=0.75;m.labels.push("虚弱 ×0.75")}if($(`buffBrute`).checked)add("strength",8,"蛮力·力量");if($(`buffBurst`).checked)add("strength",66,"高级爆发·临时力量");return m}
function calculate(){const auto=autoModifiers(),attack=Math.max(0,num("attack")),skill=Math.max(0,num("skillCoef"))/100,strength=num("strength")+auto.strength;const base=attack*skill+strength;const baseAfter=base*(1+(num("baseBonus")+auto.base)/100);const powerAfter=baseAfter*(1+(num("powerBonus")+auto.power)/100);const vulnAfter=powerAfter*(1+(num("vulnerability")+auto.vulnerability)/100);const finalAfter=vulnAfter*(1+(num("finalBonus")+auto.final)/100)*auto.damageMult;const defenseAfter=finalAfter*Math.max(0,num("defenseFactor"))/100;const normal=defenseAfter*Math.max(0,num("otherMultiplier"));const critMult=Math.max(0,num("critDamage")+auto.critDamage)/100,crit=normal*critMult,cr=clamp((num("critRate")+auto.critRate)/100,0,1),expected=normal*(1-cr)+crit*cr;const value={normal,crit,expected}[resultMode],labels={normal:"非暴击伤害",crit:"暴击伤害",expected:"期望伤害"};$(`resultLabel`).textContent=`${$(`charSelect`).value} · ${labels[resultMode]}`;$(`resultNumber`).textContent=fmt(value);$(`normalLine`).textContent=`非暴击：${fmt(normal)}`;$(`critLine`).textContent=`暴击：${fmt(crit)}`;$(`expectedLine`).textContent=`期望：${fmt(expected)}`;$(`formula`).textContent=`(${fmt(attack)} × ${skill.toFixed(3)} + ${fmt(strength)}) × ${(1+(num("baseBonus")+auto.base)/100).toFixed(3)} × ${(1+(num("powerBonus")+auto.power)/100).toFixed(3)} × ${(1+(num("vulnerability")+auto.vulnerability)/100).toFixed(3)} × ${(1+(num("finalBonus")+auto.final)/100).toFixed(3)} × ${auto.damageMult.toFixed(3)} × ${(Math.max(0,num("defenseFactor"))/100).toFixed(3)} × ${Math.max(0,num("otherMultiplier")).toFixed(3)}`;const steps=[["攻击 × 技能倍率 + 力量",base],["× 基础伤害增幅",baseAfter],["× Power / 伤害强效",powerAfter],["× Vulnerability / 易伤",vulnAfter],["× 最终伤害 / 虚弱",finalAfter],["× 防御后系数",defenseAfter],["× 其他独立乘区",normal]];$(`breakdown`).innerHTML=steps.map(([k,v])=>`<div class="step"><span>${k}</span><strong>${fmt(v)}</strong></div>`).join("");$(`autoSummary`).innerHTML=(auto.labels.length?auto.labels:["当前无自动加成"]).map(x=>`<span class="chip">${escapeHTML(x)}</span>`).join("")}
function resetCalc(){const defaults={attack:1000,strength:0,skillCoef:200,baseBonus:0,powerBonus:0,vulnerability:0,finalBonus:0,critRate:0,critDamage:150,defenseFactor:100,otherMultiplier:1};for(const [id,v] of Object.entries(defaults))$(id).value=v;for(const id of ["buffVuln","buffWeak","buffBrute","buffBurst","contractConditional"])$(id).checked=false;$(`fateSelect`).value="";$(`contractSelect`).value="";$(`contractPieces`).value="0";fateAuto={};contractAuto={};$(`charSelect`).value="莱克";loadCharacter();loadFate();loadContract();calculate()}
function hashString(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function pick(arr,seed,offset=0){return arr[(seed+offset*2654435761>>>0)%arr.length]}function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
async function loadWikiImage(name){const img=$("fortunePortrait");img.hidden=true;img.removeAttribute("src");const api=`https://morimens.huijiwiki.com/api.php?action=query&format=json&origin=*&prop=pageimages&piprop=thumbnail&pithumbsize=900&titles=${encodeURIComponent(name)}`;try{const c=new AbortController();setTimeout(()=>c.abort(),4500);const r=await fetch(api,{signal:c.signal});if(!r.ok)throw new Error();const j=await r.json();const page=Object.values(j.query?.pages||{})[0],src=page?.thumbnail?.source;if(!src)throw new Error();img.onload=()=>img.hidden=false;img.onerror=()=>img.hidden=true;img.src=src}catch(e){img.hidden=true}}
function renderFortune(random=false){const date=todayKey(),seed=hashString(`${date}:${random?++rerollSalt:0}`),name=pick(CHARACTERS,seed,1),level=pick(LEVELS,seed,2);$("fortuneDate").textContent=`${date} · 守密人每日签`;$("fortuneTitle").textContent=name;$("fortuneInitial").textContent=name.replace(/[「」·]/g,"").slice(0,1)||"夜";$("fortuneLevel").textContent=level;$("fortuneText").textContent=pick(FORTUNES,seed,3);$("fortuneQuote").textContent=SHORT_QUOTES[name]?`角色短句：${SHORT_QUOTES[name]}`:"今日角色短句未内置；可前往维基查看完整语音与档案。";$("fortuneGood").textContent=pick(GOOD,seed,4);$("fortuneBad").textContent=pick(BAD,seed,5);$("fortuneStat").textContent=pick(STATS,seed,6);$("fortuneKeyword").textContent=pick(KEYWORDS,seed,7);$("wikiBtn").href=wikiUrl(name);loadWikiImage(name)}

document.querySelectorAll(".modeBtn").forEach(btn=>btn.addEventListener("click",()=>{resultMode=btn.dataset.mode;document.querySelectorAll(".modeBtn").forEach(x=>x.setAttribute("aria-pressed",String(x===btn)));calculate()}));
for(const id of ["attack","strength","skillCoef","baseBonus","powerBonus","vulnerability","finalBonus","critRate","critDamage","defenseFactor","otherMultiplier","contractPieces","contractConditional","buffVuln","buffWeak","buffBrute","buffBurst"])$(id).addEventListener("input",calculate);
$("charSelect").addEventListener("change",loadCharacter);$("skillSelect").addEventListener("change",updateSkillLevels);$("skillLevel").addEventListener("change",applySelectedSkill);$("fateSelect").addEventListener("change",loadFate);$("contractSelect").addEventListener("change",loadContract);$("calcBtn").addEventListener("click",calculate);$("resetBtn").addEventListener("click",resetCalc);$("fortuneBtn").addEventListener("click",()=>renderFortune(false));$("rerollBtn").addEventListener("click",()=>renderFortune(true));
populateCharacters();loadCharacter();calculate();renderFortune(false);loadCategoryOptions("命轮","fateSelect",["陨日","虔诚的伟力"]);loadCategoryOptions("密契","contractSelect",["四月礼赞","荒原狼","猩红之悸","再衍化"]);
