(()=>{
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:'—';
  const zh=()=>localStorage.getItem('morimens.language')!=='en';
  const rankCaps=[50,200,500,1000];
  const difficultyOrder=['normal','hard','nightmare','madness'];
  const difficultyZh={all:'全部难度',normal:'普通',hard:'困难',nightmare:'噩梦',madness:'癫狂',unknown:'未识别'};
  const enlightOrder=['e3','overlimit','law12'];
  const enlightZh={e3:'最高三启',overlimit:'最高超限',law12:'最高+12法则'};
  let manifest=null,season=null,stats=null,awakenerMap=new Map(),filtersReady=false,searchPerformed=false;

  function injectStyle(){
    if($('morimensDtideStyle'))return;
    const s=document.createElement('style');s.id='morimensDtideStyle';s.textContent=`
      .morimensTabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 18px;padding:6px;border:1px solid rgba(148,163,184,.16);border-radius:15px;background:rgba(15,23,42,.65);position:sticky;top:8px;z-index:40;backdrop-filter:blur(12px)}
      .morimensTab{border:1px solid transparent;border-radius:10px;padding:10px 15px;background:transparent;color:#9eabba;cursor:pointer;font:700 13px/1.2 inherit}.morimensTab[aria-selected="true"]{color:#f1ddb5;border-color:rgba(213,177,118,.36);background:rgba(213,177,118,.12)}
      .dtideHero{display:flex;gap:12px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap}.dtideControls{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:16px}.dtideFilters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.dtideField{display:flex;flex-direction:column;gap:6px}.dtideField.span2{grid-column:span 2}.dtideField label{font-size:11px;color:#98a4b6}.dtideField input,.dtideField select{min-height:40px;border:1px solid #334155;border-radius:10px;background:#111827;color:#edf2f7;padding:8px 10px}.dtideField select[multiple]{min-height:132px}.dtideField small{font-size:10px;color:#718096;line-height:1.45}
      .dtideStatGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.dtideStat{padding:13px;border-radius:12px;background:rgba(255,255,255,.035);border:1px solid rgba(148,163,184,.12)}.dtideStat small{display:block;color:#8290a2;font-size:10px}.dtideStat strong{display:block;margin-top:4px;font-size:20px;color:#f1dfbc}
      .dtideSection{margin-top:18px}.dtideSection h3{font-size:15px;margin:0 0 10px;color:#ead9b9}.dtideSubhead{display:flex;justify-content:space-between;align-items:end;gap:10px;flex-wrap:wrap;margin:0 0 10px}.dtideLeaderboardTabs{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 10px}.dtideLeaderboardTab{border:1px solid rgba(148,163,184,.22);border-radius:9px;background:#111827;color:#aeb8c7;padding:7px 14px;font:inherit;font-size:12px;font-weight:800;cursor:pointer}.dtideLeaderboardTab[aria-selected="true"]{border-color:#b99a61;background:rgba(185,154,97,.16);color:#f1d69f}.dtideScroll{overflow:auto;border:1px solid rgba(148,163,184,.13);border-radius:12px}.dtideTable{width:100%;border-collapse:collapse;min-width:720px}.dtideTable th,.dtideTable td{padding:9px 10px;border-bottom:1px solid rgba(148,163,184,.1);text-align:left;font-size:11px}.dtideTable th{position:sticky;top:0;background:#111827;color:#aeb8c7;z-index:1}.dtideTable td{color:#d4dbe5}.dtideHeat{background:var(--dtide-heat,transparent);transition:background-color .18s ease}.dtideGearIcon{width:30px;height:30px;border-radius:7px;object-fit:cover;background:#0b1220;flex:none}.dtideSortHead,.dtideMatrixCharacter{border:0;background:transparent;color:inherit;font:inherit;font-weight:700;padding:0;cursor:pointer}.dtideSortHead:hover,.dtideMatrixCharacter:hover{color:#f1d69f}.dtideMatrixCharacter{width:100%;text-align:left}.dtideTable tr:last-child td{border-bottom:0}.dtideRate{font-variant-numeric:tabular-nums;color:#f1d69f;font-weight:800}.dtideChar{display:flex;align-items:center;gap:8px;min-width:130px}.dtideChar img{width:30px;height:30px;border-radius:8px;object-fit:cover;background:#0b1220}.dtideEnlightBar{display:flex;width:72px;height:6px;margin-left:2px;border-radius:99px;overflow:hidden;background:#263244;box-shadow:inset 0 0 0 1px rgba(255,255,255,.12);flex:none}.dtideEnlightBar span{height:100%;min-width:1px}
      .dtideRankedItem{display:flex;align-items:center;gap:8px}.dtideRankedItem>.dtideMatrixCharacter{width:auto;min-width:0;flex:1 1 auto}.dtideRankedItem>.dtideEnlightBar{margin-left:auto}.dtideEntityHead{display:flex;align-items:center;justify-content:space-between;gap:12px}.dtideEnlightLegend{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap;font-size:9px;font-weight:600;color:#9da8b8}.dtideEnlightLegend span{display:inline-flex;align-items:center;gap:3px;white-space:nowrap}.dtideEnlightLegend i{width:9px;height:5px;border-radius:2px}.dtideRankMark{width:38px;flex:0 0 38px;text-align:center;font-variant-numeric:tabular-nums}.dtideRankMark>b{display:block;color:#dbe3ee;font-size:12px}.dtideRankMark>small{display:block;margin-top:2px;font-size:9px;font-weight:800;white-space:nowrap}.dtideRankUp{color:#36d17c}.dtideRankDown{color:#f15b69}.dtideRankSame{color:#7f8a9c}.dtideRankNew{color:#55b6ff}
      .dtideUsageCards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.dtideUsage{padding:10px;border:1px solid rgba(148,163,184,.12);border-radius:11px;background:rgba(255,255,255,.028);display:flex;justify-content:space-between;gap:10px;align-items:center}.dtideUsage b{font-size:12px}.dtideUsage small{display:block;color:#77869a;margin-top:3px}.dtideUsage strong{font-size:15px;color:#e9d0a0;white-space:nowrap}.dtideMemberAvatar{width:30px;height:30px;border-radius:8px;object-fit:cover;float:left;margin:0 7px 3px 0;background:#0b1220}
      .dtideResults{display:grid;gap:9px}.dtideResult{padding:12px;border:1px solid rgba(148,163,184,.14);border-radius:13px;background:rgba(255,255,255,.025)}.dtideResultHead{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.dtideResultHead b{font-size:13px}.dtideResultHead a{font-size:11px;color:#d5b176}.dtideMembers{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:9px}.dtideMember{padding:8px;border-radius:9px;background:#111827;min-width:0}.dtideMember b{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;display:block}.dtideMember small{display:block;color:#7f8da1;margin-top:3px;font-size:9px;line-height:1.45}.dtideBorrow{color:#d7a85b!important}.dtideGear{color:#b8c4d6!important}.dtideNotice{padding:11px 12px;border-radius:11px;border:1px solid rgba(215,168,91,.25);background:rgba(215,168,91,.07);color:#b9c3d0;font-size:11px;line-height:1.65}.dtideEmpty{padding:22px;text-align:center;color:#7f8da1;font-size:12px}.dtideActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.dtidePager{display:flex;gap:8px;align-items:center;justify-content:flex-end;margin-top:10px;color:#8290a2;font-size:11px}.dtideGearSummary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:10px}.dtideGearSummary>div{padding:10px;border:1px solid rgba(148,163,184,.12);border-radius:10px;background:rgba(255,255,255,.02)}.dtideGearSummary small{display:block;color:#77869a;font-size:9px}.dtideGearSummary b{font-size:13px;color:#e8d4ae}.dtideCompareGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.dtideCoverageWarn{margin-top:10px}
      @media(max-width:900px){.dtideControls,.dtideFilters{grid-template-columns:repeat(2,minmax(0,1fr))}.dtideUsageCards{grid-template-columns:repeat(2,minmax(0,1fr))}.dtideMembers{grid-template-columns:repeat(2,minmax(0,1fr))}.dtideCompareGrid{grid-template-columns:1fr}}
      @media(max-width:580px){.morimensTabs{position:static}.dtideControls,.dtideFilters,.dtideStatGrid,.dtideUsageCards,.dtideGearSummary{grid-template-columns:1fr}.dtideField.span2{grid-column:auto}.dtideMembers{grid-template-columns:1fr}}
    `;document.head.appendChild(s);
  }

  function setupTabs(){
    const main=document.querySelector('main.wrap'),hero=main?.querySelector('.hero'),grid=main?.querySelector('.grid2');if(!main||!hero||!grid||$('morimensTabs'))return;
    const standalone=document.body.dataset.morimensStandalone||'';
    const source=Array.from(main.children).find(x=>x!==hero&&x!==grid&&x.matches?.('section.panel'))||null;
    const tabs=document.createElement('nav');tabs.id='morimensTabs';tabs.className='morimensTabs';tabs.setAttribute('role','tablist');tabs.innerHTML='<button class="morimensTab" id="morimensDtideTab" role="tab" aria-selected="true" aria-controls="morimensDtidePanel">融灾榜单</button><button class="morimensTab" id="morimensCalcTab" role="tab" aria-selected="false" aria-controls="morimensCalcPanel">伤害计算器</button><button class="morimensTab" id="morimensFortuneTab" role="tab" aria-selected="false" aria-controls="morimensFortunePanel">每日签</button><button class="morimensTab" id="morimensAboutTab" role="tab" aria-selected="false" aria-controls="morimensAboutPanel">关于</button>';
    const calc=document.createElement('div');calc.id='morimensCalcPanel';calc.setAttribute('role','tabpanel');calc.appendChild(grid.querySelector('[aria-labelledby="calcTitle"]'));
    const fortune=document.createElement('div');fortune.id='morimensFortunePanel';fortune.setAttribute('role','tabpanel');fortune.hidden=true;fortune.appendChild(grid.querySelector('.fortuneCard'));
    if(standalone==='calc'||standalone==='fortune'){hero.remove();main.querySelector('.topbar')?.remove();grid.remove();if(standalone==='calc'){main.appendChild(calc)}else{main.appendChild(fortune);fortune.hidden=false}return;}
    if(source)calc.appendChild(source);
    const dtide=document.createElement('div');dtide.id='morimensDtidePanel';dtide.setAttribute('role','tabpanel');dtide.innerHTML=panelHtml();
    const about=document.createElement('div');about.id='morimensAboutPanel';about.setAttribute('role','tabpanel');about.hidden=true;about.innerHTML=aboutHtml();
    hero.after(tabs,dtide,calc,fortune,about);$('morimensBootShell')?.remove();document.body.classList.remove('morimensBooting');dtide.querySelector('.dtideLeaderboardTabs')?.addEventListener('click',e=>{const tab=e.target.closest('[data-dtide-entity]');if(!tab)return;const field=$('dtideEntityType'),entity=tab.dataset.dtideEntity;if(!field||field.value===entity)return;dtide.querySelectorAll('[data-dtide-entity]').forEach(x=>x.setAttribute('aria-selected',String(x===tab)));field.value=entity;const title=$('dtideMatrixTitle'),host=$('dtideMatrix'),label=entity==='wheel'?'命轮':entity==='creation'?'造物':'角色';if(title)title.textContent=label+'逐波出场率';if(host)host.setAttribute('aria-busy','true');requestAnimationFrame(()=>field.dispatchEvent(new Event('change',{bubbles:true})))});
    const activate=name=>{const isD=name==='dtide',isC=name==='calc',isF=name==='fortune',isA=name==='about';for(const [id,on] of [['morimensDtideTab',isD],['morimensCalcTab',isC],['morimensFortuneTab',isF],['morimensAboutTab',isA]])$(id).setAttribute('aria-selected',String(on));dtide.hidden=!isD;calc.hidden=!isC;fortune.hidden=!isF;about.hidden=!isA;history.replaceState(null,'',`#${name}`);if(isD)loadOnce()};
    $('morimensDtideTab').addEventListener('click',()=>activate('dtide'));$('morimensCalcTab').addEventListener('click',()=>activate('calc'));$('morimensFortuneTab').addEventListener('click',()=>activate('fortune'));$('morimensAboutTab').addEventListener('click',()=>activate('about'));activate(['#calc','#fortune','#about'].includes(location.hash)?location.hash.slice(1):'dtide');
  }

  function aboutHtml(){return `
    <section class="panel" aria-labelledby="morimensAboutTitle">
      <div class="panelHead"><div><p class="eyebrow">ABOUT · CREDITS</p><h2 id="morimensAboutTitle">关于忘却前夜工具箱</h2><p class="panelLead">本工具箱为《忘却前夜》玩家制作的粉丝向项目，免费使用，不进行任何商业化运营。</p></div><span class="statusPill">非官方 · 非商业</span></div>
      <div class="sourceList">
        <div class="sourceItem"><strong>数据与资料来源</strong><br>感谢 <a href="https://eremora.com/leaderboard/abyss" target="_blank" rel="noopener noreferrer">Eremora</a> 提供融灾榜单与挑战记录；感谢 <a href="https://github.com/dansa/SKeyDB" target="_blank" rel="noopener noreferrer">dansa/SKeyDB</a> 提供角色、技能、命轮及密契等结构化数据；感谢 <a href="https://morimens.huijiwiki.com/" target="_blank" rel="noopener noreferrer">忘却前夜中文维基</a> 提供中文名称、资料与文本参考。</div>
        <div class="sourceItem"><strong>特别说明</strong><br>本页面不是官方产品，与游戏官方及上述数据网站不存在隶属或商业合作关系。《忘却前夜》相关角色、图片、文本及其他素材版权归各自权利方所有；本站仅用于玩家交流与资料查询。</div>
        <div class="sourceItem"><strong>制作者</strong><br>B站：<a href="https://space.bilibili.com/95687310?spm_id_from=333.1007.0.0" target="_blank" rel="noopener noreferrer">@青灯不弈</a></div>
      </div>
    </section>
  `}

  function panelHtml(){return `
    <section class="panel" aria-labelledby="dtideTitle">
      <div class="dtideHero"><div><p class="eyebrow">EREMORA · D-ZONE ANALYTICS</p><h2 id="dtideTitle">融灾榜单</h2><p class="panelLead">更新时间节点：显示当前结构化融灾数据的同步时间；出场率可按榜单 Top50 / Top200 / Top500 / Top1000 与普通 / 困难 / 噩梦 / 癫狂四档难度分别统计。</p></div><span class="statusPill" id="dtideStatus">等待数据</span></div>
      <div class="dtideControls">
        <div class="dtideField"><label>期次</label><select id="dtideSeason"></select></div>
        <div class="dtideField"><label>榜单范围</label><select id="dtideRankScope">${rankCaps.map(x=>`<option value="${x}">Top ${x}</option>`).join('')}</select></div>
        <div class="dtideField"><label>难度</label><select id="dtideDifficulty"><option value="all">全部难度</option>${difficultyOrder.map(x=>`<option value="${x}">${difficultyZh[x]}</option>`).join('')}</select></div>
        <div class="dtideField"><label>融灾总得分</label><select id="dtideTotalScore"><option value="0">全部分数</option><option value="300">300 分以上</option><option value="400">400 分以上</option><option value="500">500 分以上</option><option value="600">600 分以上</option><option value="700">700 分以上</option></select></div><input id="dtideWave" type="hidden" value="all"><input id="dtideEntityType" type="hidden" value="character">
        <input id="dtideClearType" type="hidden" value="all">
        <input id="dtideRateMode" type="hidden" value="team">
      </div>
      <div class="dtideStatGrid" id="dtideSummary"></div>
      <div id="dtideCoverageWarn" class="dtideCoverageWarn"></div>
      <div class="dtideSection"><h3 id="dtideMatrixTitle">角色逐波出场率</h3><div class="dtideLeaderboardTabs" role="tablist" aria-label="出场率榜单类型"><button type="button" class="dtideLeaderboardTab" data-dtide-entity="character" role="tab" aria-selected="true">角色榜单</button><button type="button" class="dtideLeaderboardTab" data-dtide-entity="wheel" role="tab" aria-selected="false">命轮榜单</button><button type="button" class="dtideLeaderboardTab" data-dtide-entity="creation" role="tab" aria-selected="false">造物榜单</button><label class="dtideCreationFilter"><input type="checkbox" id="dtideCreationFilter"> 筛选造物</label></div><div class="dtideScroll" id="dtideMatrix"></div></div>
    </section>
    <section class="panel">
      <div class="panelHead"><div><h2>搜索配队</h2><p class="panelLead">筛选条件作用于公开的融灾队伍记录；选择角色后可进一步查看其常用队友、命轮与密契。</p></div><span class="statusPill" id="dtideFilterCoverage">字段覆盖检查中</span></div>
      <div class="dtideFilters" style="margin-top:15px">
        <div class="dtideField span2"><label>包含角色（可多选）</label><select id="dtideCharacters" multiple></select><small>Windows：Ctrl / Shift 多选。可设置“全部包含”或“任一包含”。</small></div>
        <div class="dtideField"><label>角色匹配方式</label><select id="dtideCharacterMode"><option value="all">包含全部所选角色</option><option value="any">包含任一所选角色</option></select></div>
        <div class="dtideField"><label>排除角色（可多选）</label><select id="dtideExcludeCharacters" multiple></select></div>
        <div class="dtideField"><label>最低角色等级</label><input id="dtideLevelMin" type="number" min="1" placeholder="不限"></div>
        <div class="dtideField"><label>最高角色等级</label><input id="dtideLevelMax" type="number" min="1" placeholder="不限"></div>
        <div class="dtideField"><label>启灵分组</label><select id="dtideProgression"><option value="">不限</option>${enlightOrder.map(x=>`<option value="${x}">${enlightZh[x]}</option>`).join('')}</select></div>
        <div class="dtideField"><label>借用助战</label><select id="dtideBorrowed"><option value="">不限</option><option value="yes">队伍包含助战</option><option value="no">队伍不含助战</option></select></div>
        <div class="dtideField"><label>命轮</label><select id="dtideWheel"><option value="">不限</option></select></div>
        <div class="dtideField"><label>密契套装</label><select id="dtideCovenant"><option value="">不限</option></select></div>
        <div class="dtideField"><label>最低密契评分</label><input id="dtideCovenantScoreMin" type="number" min="0" placeholder="不限"></div>
        <div class="dtideField"><label>最高密契评分</label><input id="dtideCovenantScoreMax" type="number" min="0" placeholder="不限"></div>
        <div class="dtideField"><label>最低榜单分</label><input id="dtideScoreMin" type="number" min="0" placeholder="不限"></div>
        <div class="dtideField"><label>最高榜单排名</label><input id="dtideRankMax" type="number" min="1" max="1000" placeholder="例如 200"></div>
      </div>
      <div class="dtideActions"><button class="primaryBtn" id="dtideSearch" type="button">搜索配队</button><button class="ghostBtn" id="dtideReset" type="button">清空筛选</button></div>
      <div class="dtideSection"><div class="dtideResults" id="dtideResults"></div><div class="dtidePager" id="dtidePager"></div></div>
    </section>
  `}

  async function waitMorimensData(){if(window.MorimensData?.db?.records&&window.MorimensData?.identityDb?.bySkeydbId)return;await new Promise(resolve=>{const t=setTimeout(resolve,5000);window.addEventListener('morimens-data-ready',()=>{clearTimeout(t);resolve()},{once:true})})}
  function displayCharacterName(...values){return values.find(value=>{const name=String(value||'').trim();return name&&!/^(awakener(?:-\d+)?|unknown|角色|唤醒体)$/i.test(name)})||'未知'}
  function characterInfo(key,fallback={}){
    const data=window.MorimensData,liveRecords=data?.db?.records||[];
    const rec=liveRecords.find(x=>x.id===key||x.ingameId===key||x.ingameId===fallback.ingameId)||awakenerMap.get(key)||Array.from(awakenerMap.values()).find(x=>x.ingameId===key)||null;
    const id=rec?.id||fallback.skeydbId||(/^awakener-\d+$/i.test(String(key||''))?key:null),identity=data?.identityDb?.bySkeydbId?.[id]||data?.zhDb?.bySkeydbId?.[id],loc=rec&&data?.localizedProfile?.(rec);
    return {name:displayCharacterName(identity?.name,loc?.name,fallback.canonicalName,fallback.name,rec?.name),image:rec?.assets?.portrait||fallback.image||'',id:id||key,ingameId:rec?.ingameId||fallback.ingameId};
  }
  function wheelName(item){return window.MorimensData?.localizedEntity?.('wheel',item)?.name||item?.name||item?.id||'未知命轮'}
  const memberKey=m=>m.skeydbId||m.ingameId||m.id||m.name;
  function difficultyOf(team,wave){const raw=String(team?.difficulty||team?.stageName||wave?.difficulty||wave?.stageName||'').toLowerCase();for(const d of difficultyOrder)if(new RegExp(`(?:^|[^a-z])${d}(?:$|[^a-z])`,'i').test(raw))return d;return 'unknown'}
  function enlightClass(m){const ms=String(m?.enlightenMilestone||m?.enlightTier||m?.progression||'').toUpperCase();if(ms==='AA'||ms==='LAW12')return 'law12';if(ms==='OE'||ms==='OVERLIMIT')return 'overlimit';return 'e3'}
  function maxRankAvailable(){const rs=(season?.records||[]).map(r=>Number(r.rank)).filter(Number.isFinite);return rs.length?Math.max(...rs):(season?.recordCount||season?.records?.length||0)}
  function getSelectedValues(id){return Array.from($(id)?.selectedOptions||[]).map(x=>x.value).filter(Boolean)}
  function flattenTeams(){
    const unique=new Map();
    const richness=t=>(t.token?8:0)+(t.creations?.length||0)*3+(t.members||[]).reduce((sum,m)=>sum+(m.wheels?.length||m.weapons?.length||0)*4+(m.covenants?.length||m.suits?.length||(m.covenant?1:0))*4+(m.covenantScore!=null?2:0)+(m.level!=null?1:0)+(m.enlightenment?.length||0),0);
    for(const record of season?.records||[])for(const wave of record.waves||[])for(const team of wave.teams||[]){
      const difficulty=difficultyOf(team,wave),members=(team.members||[]).map(m=>String(m.ingameId||m.skeydbId||m.id||m.canonicalName||m.name||'')).filter(Boolean).sort().join(',');
      const key=[record.uid||record.rank||'',wave.wave||'',team.clearType||'',difficulty,members].join('|'),row={record,wave,team,difficulty},old=unique.get(key);
      if(!old||richness(team)>richness(old.team))unique.set(key,row);
    }
    return [...unique.values()];
  }
  function scopedRows({wave='all',ct=$('dtideClearType')?.value||'all',difficulty=$('dtideDifficulty')?.value||'all',rankCap=Number($('dtideRankScope')?.value||50),scoreMin=Number($('dtideTotalScore')?.value||0)}={}){return flattenTeams().filter(x=>{
    if(rankCap&&(!Number.isFinite(Number(x.record.rank))||Number(x.record.rank)>rankCap))return false;
    if(wave!=='all'&&Number(wave)!==Number(x.wave.wave))return false;
    if(ct!=='all'&&ct!==x.team.clearType)return false;
    if(difficulty!=='all'&&difficulty!==x.difficulty)return false;
    if(scoreMin&&Number(x.record.score||0)<scoreMin)return false;
    return true;
  })}
  function countRate(map,key,meta={}){if(key==null||key==='')return;const k=String(key),x=map.get(k)||{key:k,count:0,...meta};x.count++;map.set(k,x)}
  function computeGroup(rows){
    const chars=new Map(),wheels=new Map(),covs=new Map(),byChar=new Map(),enlight=new Map();let memberSlots=0,wheelSlots=0,covenantSlots=0;
    for(const {team} of rows){const seenC=new Set(),seenW=new Set(),seenS=new Set();for(const m of team.members||[]){memberSlots++;const ck=String(memberKey(m)),ec=enlightClass(m);countRate(enlight,ec,{name:enlightZh[ec]});if(!seenC.has(ck)){seenC.add(ck);countRate(chars,ck,{id:m.skeydbId||null,ingameId:m.ingameId||null,name:characterInfo(ck,m).name,image:m.image||null})}let bc=byChar.get(ck);if(!bc){bc={key:ck,id:m.skeydbId||null,ingameId:m.ingameId||null,name:characterInfo(ck,m).name,image:m.image||null,appearances:0,levels:[],enlight:new Map(),wheels:new Map(),covs:new Map()};byChar.set(ck,bc)}bc.appearances++;if(m.level!=null)bc.levels.push(Number(m.level));countRate(bc.enlight,ec,{name:enlightZh[ec]});for(const w of m.wheels||[]){wheelSlots++;const wk=w.id??w.name;if(wk==null)continue;if(!seenW.has(String(wk))){seenW.add(String(wk));countRate(wheels,wk,{id:w.id??null,name:wheelName(w),image:w.image||null})}countRate(bc.wheels,wk,{id:w.id??null,name:wheelName(w),image:w.image||null})}for(const c of m.covenants||((m.covenant)?[m.covenant]:[])){covenantSlots++;const sk=c.id??c.name;if(sk==null)continue;if(!seenS.has(String(sk))){seenS.add(String(sk));countRate(covs,sk,{id:c.id??null,name:c.name||sk,image:c.image||null})}countRate(bc.covs,sk,{id:c.id??null,name:c.name||sk,image:c.image||null})}}}
    const teamCount=rows.length,finish=map=>[...map.values()].map(x=>({...x,teamRatePct:teamCount?x.count/teamCount*100:0})).sort((a,b)=>b.count-a.count);
    const teammateCounts=new Map();for(const {team} of rows){const keys=[...new Set((team.members||[]).map(memberKey))];for(const a of keys)for(const b of keys)if(a&&b&&a!==b){const m=teammateCounts.get(a)||new Map();m.set(b,(m.get(b)||0)+1);teammateCounts.set(a,m)}}
    const byCharacter=byChar;
    const bc=[...byCharacter.values()].map(x=>({...x,level:{min:x.levels.length?Math.min(...x.levels):null,max:x.levels.length?Math.max(...x.levels):null,avg:x.levels.length?x.levels.reduce((a,b)=>a+b,0)/x.levels.length:null},teammates:[...(teammateCounts.get(x.key)||new Map())].map(([key,count])=>({key,count,ratePct:x.appearances?count/x.appearances*100:0,name:characterInfo(key).name})).sort((a,b)=>b.count-a.count),enlight:[...x.enlight.values()].map(v=>({...v,ratePct:x.appearances?v.count/x.appearances*100:0})).sort((a,b)=>b.count-a.count),wheels:[...x.wheels.values()].map(v=>({...v,ratePct:x.appearances?v.count/x.appearances*100:0})).sort((a,b)=>b.count-a.count),covenants:[...x.covs.values()].map(v=>({...v,ratePct:x.appearances?v.count/x.appearances*100:0})).sort((a,b)=>b.count-a.count)})).sort((a,b)=>b.appearances-a.appearances);
    return {teamCount,memberSlots,wheelSlots,covenantSlots,characters:finish(chars),wheels:finish(wheels),covenants:finish(covs),enlight:finish(enlight),byCharacter:bc};
  }
  function currentGroup(overrides={}){return computeGroup(scopedRows(overrides))}

  function renderCoverage(){
    const cap=Number($('dtideRankScope').value||50),max=maxRankAvailable(),complete=max>=cap;
    $('dtideCoverageWarn').innerHTML=complete?'':`<div class="dtideNotice">当前快照实际抓取到的最高榜单名次为 <b>#${esc(max||'—')}</b>。Top ${cap} 统计目前属于不完整样本；页面不会把现有记录标记成完整 Top ${cap}。后续同步抓到更深排名后会自动转为完整口径。</div>`;
    for(const opt of $('dtideRankScope').options){const n=Number(opt.value),ok=max>=n;opt.textContent=`Top ${n}${ok?'':' · 当前样本不足'}`}
  }
  function renderSummary(){const g=currentGroup(),coverage=manifest.fieldCoverage||{},cap=Number($('dtideRankScope').value||50),max=maxRankAvailable();$('dtideSummary').innerHTML=[['榜单样本',`${season.recordCount} 条 / 最深 #${max||'—'}`],['当前 Top 口径',`Top ${cap}`],['统计队伍',g.teamCount],['角色槽位',g.memberSlots]].map(([a,b])=>`<div class="dtideStat"><small>${a}</small><strong>${esc(b)}</strong></div>`).join('');$('dtideStatus').textContent=`第 ${season.seasonId} 期 · ${difficultyZh[$('dtideDifficulty').value]||'全部难度'} · Top ${cap}`;$('dtideFilterCoverage').textContent=`等级 ✓ · 启灵 ${coverage.enlightenLevel?'✓':'—'} · 命轮 ${coverage.wheels?'✓':'—'} · 密契 ${coverage.covenants?'✓':'—'}`;renderCoverage()}
function sortUsageRows(a,b,groups,waves){const spec=$('dtideSort')?.value||'total-desc';const m=spec.match(/^wave(\d+)-(asc|desc)$/);let av=a.total||a.count||0,bv=b.total||b.count||0;if(m){const w=Number(m[1]),g=groups?.get(w),find=x=>g?.characters?.find(y=>y.key===x.key)?.count||0;av=find(a);bv=find(b)}const d=bv-av;return spec.endsWith('-asc')?-d:d||String(a.name||a.key).localeCompare(String(b.name||b.key),'zh-CN')}
  function renderMatrix(){
    const cap=Number($('dtideRankScope')?.value||50),difficulty=$('dtideDifficulty')?.value||'all',ct=$('dtideClearType')?.value||'all',mode=$('dtideRateMode')?.value||'team';
    const all=scopedRows({cap,difficulty,wave:'all',clearType:ct}),waves=[...new Set(all.map(x=>Number(x.wave.wave)).filter(Number.isFinite))].sort((a,b)=>a-b),groups=new Map(waves.map(w=>[w,computeGroup(all.filter(x=>Number(x.wave.wave)===w))])),union=new Map();
    for(const [,g] of groups)for(const c of g.characters)union.set(c.key,c);
    const sortKey=window.__dtideMatrixSort||'total',asc=window.__dtideMatrixAsc||false;
    const rows=[...union.values()].map(c=>({...c,total:waves.reduce((s,w)=>s+(groups.get(w)?.characters.find(x=>x.key===c.key)?.count||0),0)}));
    rows.sort((a,b)=>{const av=sortKey==='total'?a.total:(groups.get(Number(sortKey))?.characters.find(x=>x.key===a.key)?.count||0),bv=sortKey==='total'?b.total:(groups.get(Number(sortKey))?.characters.find(x=>x.key===b.key)?.count||0),d=bv-av;return (asc?-d:d)||String(a.name||a.key).localeCompare(String(b.name||b.key),'zh-CN')});
    const arrow=k=>k===sortKey?(asc?' ↑':' ↓'):' ↕',host=$('dtideMatrix');if(!host)return;if(!rows.length){host.innerHTML='<div class="dtideEmpty">当前口径暂无记录。</div>';return}
    const enlightColors={e3:'#d9a441',overlimit:'#62b7ff',law12:'#d978d0',unknown:'#6b7280'};
    const enlightLabel={e3:'最高三启',overlimit:'最高超限',law12:'最高+12法则',unknown:'未知'};
    const enlightBar=c=>{let items=(Array.isArray(c.enlight)?c.enlight:[]).filter(x=>Number(x.count)>0);if(!items.length)items=[{key:"unknown",name:"启灵数据缺失",count:c.count||1}];const total=items.reduce((s,x)=>s+Number(x.count||0),0)||1;return `<div class="dtideEnlightBar" title="${items.map(x=>`${enlightLabel[x.key]||x.name||'未知'} ${pct(Number(x.count||0)/total*100)}`).join(' · ')}">${items.map(x=>{const key=x.key||x.id||'unknown';return `<span style="width:${Number(x.count||0)/total*100}%;background:${enlightColors[key]||enlightColors.unknown}"></span>`}).join('')}</div>`};
    const characterEnlight=new Map();
    for(const [,g] of groups){for(const c of g.byCharacter||[]){const item=characterEnlight.get(c.key)||{count:0,enlight:new Map()};item.count+=c.appearances||0;for(const e of c.enlight||[]){const old=item.enlight.get(e.key)||{...e,count:0};old.count+=e.count||0;item.enlight.set(e.key,old)}characterEnlight.set(c.key,item)}}
    host.innerHTML=`<table class="dtideTable"><thead><tr><th>角色</th>${waves.map(w=>`<th><button type="button" class="dtideSortHead" data-sort-key="${w}" title="点击切换升降序">Wave ${w}${arrow(String(w))}</button></th>`).join('')}<th><button type="button" class="dtideSortHead" data-sort-key="total" title="点击切换升降序">总出现${arrow('total')}</button></th></tr></thead><tbody>${rows.map(c=>{const ce=characterEnlight.get(c.key);return `<tr><td><div class="dtideChar">${c.image?`<img src="${esc(c.image)}" alt="">`:''}<span>${esc(c.name)}</span>${enlightBar({...c,count:ce?.count||c.total,enlight:ce?[...ce.enlight.values()]:[]})}</div></td>${waves.map(w=>{const g=groups.get(w),hit=g?.characters.find(x=>x.key===c.key),rate=mode==='slot'?(hit?.slotRatePct||0):(hit?.teamRatePct||0);return `<td class="dtideRate">${pct(rate)}</td>`}).join('')}<td>${c.total}</td></tr>`}).join('')}</tbody></table>`;
    host.onclick=e=>{const btn=e.target.closest('[data-sort-key]');if(!btn)return;const key=String(btn.dataset.sortKey);if(window.__dtideMatrixSort===key)window.__dtideMatrixAsc=!window.__dtideMatrixAsc;else{window.__dtideMatrixSort=key;window.__dtideMatrixAsc=false}renderMatrix()};
  }
  function renderUsage(){const host=$('dtideUsage');if(!host)return;const g=currentGroup(),mode=$('dtideRateMode')?.value||'team';host.innerHTML=g.characters.slice(0,18).map((c,i)=>{const info=characterInfo(c.id||c.ingameId||c.key),rate=mode==='slot'?(g.memberSlots?c.count/g.memberSlots*100:0):c.teamRatePct;return `<button class="dtideUsage" type="button" data-character-index="${i}" title="点击展开该角色的 Top5 队友、命轮和密契出场率"><div class="dtideChar">${info.image?`<img src="${esc(info.image)}" alt="">`:''}<span><b>${esc(info.name||c.name)}</b><small>${c.count} 次 · 展开 Top5 队友 / 命轮 / 密契</small></span></div><strong>${pct(rate)}</strong></button>`}).join('')||'<div class="dtideEmpty">无角色统计。</div>'}
  function compareTable(columns,groups){
    const union=new Map();for(const g of groups)for(const c of g.characters)union.set(c.key,c);const rows=[...union.values()].map(c=>({...c,total:groups.reduce((s,g)=>s+(g.characters.find(x=>x.key===c.key)?.count||0),0)})).sort((a,b)=>b.total-a.total).slice(0,40);if(!rows.length)return '<div class="dtideEmpty">暂无记录。</div>';return `<table class="dtideTable"><thead><tr><th>角色</th>${columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(c=>{const info=characterInfo(c.id||c.ingameId||c.key);return `<tr><td>${esc(info.name||c.name)}</td>${groups.map(g=>{const hit=g.characters.find(x=>x.key===c.key);return `<td class="dtideRate">${pct(hit?.teamRatePct||0)}</td>`}).join('')}</tr>`}).join('')}</tbody></table>`}
  function renderComparisons(){return}
  function renderEquipment(){
    const g=currentGroup(),coverage=manifest.fieldCoverage||{},key=$('dtideEquipCharacter').value;if(!coverage.wheels&&!coverage.covenants){$('dtideEquipment').innerHTML='<div class="dtideNotice">当前快照尚未由结构化 __data.json 重建；下一次同步后会自动启用命轮、密契与启灵统计。</div>';return}
    const section=(title,arr,rateKey='teamRatePct',denom='支队伍')=>`<h4 style="margin:10px 0 7px;font-size:12px">${title}</h4><div class="dtideUsageCards">${(arr||[]).slice(0,24).map(x=>`<div class="dtideUsage"><div><b>${esc(x.name||x.key)}</b><small>${x.count} ${denom}</small></div><strong>${pct(x[rateKey])}</strong></div>`).join('')||'<div class="dtideEmpty">暂无</div>'}</div>`;
    if(!key){$('dtideEquipment').innerHTML=section('启灵分组 · 角色槽位分布',g.enlight)+section('命轮 · 队伍采用率',g.wheels)+section('密契套装 · 队伍采用率',g.covenants);return}
    const c=g.byCharacter.find(x=>x.key===key);if(!c){$('dtideEquipment').innerHTML='<div class="dtideEmpty">当前筛选下该角色没有记录。</div>';return}const info=characterInfo(c.id||c.ingameId||c.key),enlight=(c.enlight||[]).map(x=>`${x.name} ${x.count}`).join(' · ')||'—';$('dtideEquipment').innerHTML=`<div class="dtideGearSummary"><div><small>角色</small><b>${esc(info.name||c.name)}</b></div><div><small>出现次数 / 等级</small><b>${c.appearances} · Lv.${c.level.min??'—'}–${c.level.max??'—'}</b></div><div><small>启灵分组</small><b>${esc(enlight)}</b></div></div>`+section('最高出场率队友 Top 5',c.teammates,'ratePct','次同队')+section('该角色启灵分组',c.enlight,'ratePct','次')+section('该角色命轮采用率',c.wheels,'ratePct','次装备')+section('该角色密契套装采用率',c.covenants,'ratePct','次采用');
  }
  function populateFilters(){
    const chars=new Map();for(const {team} of flattenTeams())for(const m of team.members||[]){const k=String(memberKey(m));if(k)chars.set(k,{...characterInfo(m.skeydbId||m.ingameId||k),fallback:m.canonicalName||m.name||k})}
    const options=[...chars.entries()].sort((a,b)=>(a[1].name||a[1].fallback).localeCompare(b[1].name||b[1].fallback,'zh-CN')).map(([k,v])=>`<option value="${esc(k)}">${esc(v.name||v.fallback)}${v.ingameId?` · ${esc(v.ingameId)}`:''}</option>`).join('');$('dtideCharacters').innerHTML=options;$('dtideExcludeCharacters').innerHTML=options;for(const id of ['dtideCharacters','dtideExcludeCharacters'])for(const option of $(id)?.options||[])option.selected=false;
    const coverage=manifest.fieldCoverage||{};$('dtideProgression').disabled=!coverage.enlightenLevel;$('dtideWheel').disabled=!coverage.wheels;$('dtideCovenant').disabled=!coverage.covenants;
    const wheelNames=new Map(),covNames=new Map();for(const {team} of flattenTeams())for(const m of team.members||[]){for(const item of m.wheels||[])wheelNames.set(String(item.id??item.name),wheelName(item));for(const item of m.covenants||((m.covenant)?[m.covenant]:[]))covNames.set(String(item.id??item.name),item.name||item.id)}
    $('dtideWheel').innerHTML='<option value="">不限</option>'+[...wheelNames].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'zh-CN')).map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('');$('dtideCovenant').innerHTML='<option value="">不限</option>'+[...covNames].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'zh-CN')).map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('');filtersReady=true;
  }

  function matchesFilters(row){
    const rankCap=Number($('dtideRankScope').value||50);if(rankCap&&(!Number.isFinite(Number(row.record.rank))||Number(row.record.rank)>rankCap))return false;
    const difficulty=$('dtideDifficulty').value;if(difficulty!=='all'&&row.difficulty!==difficulty)return false;
    const totalScoreMin=Number($('dtideTotalScore')?.value||0);if(totalScoreMin&&Number(row.record.score||0)<totalScoreMin)return false;
    const ct=$('dtideClearType').value;if(ct!=='all'&&ct!==row.team.clearType)return false;
    const include=getSelectedValues('dtideCharacters'),exclude=getSelectedValues('dtideExcludeCharacters'),keys=row.team.members.map(m=>String(memberKey(m))),mode=$('dtideCharacterMode').value;if(include.length&&!(mode==='all'?include.every(x=>keys.includes(x)):include.some(x=>keys.includes(x))))return false;if(exclude.some(x=>keys.includes(x)))return false;
    const targets=include.length?row.team.members.filter(m=>include.includes(String(memberKey(m)))):row.team.members;
    const minLv=Number($('dtideLevelMin').value||0),maxLv=Number($('dtideLevelMax').value||0);if(minLv&&targets.some(m=>m.level==null||Number(m.level)<minLv))return false;if(maxLv&&targets.some(m=>m.level==null||Number(m.level)>maxLv))return false;
    const prog=$('dtideProgression').value;if(prog&&!targets.some(m=>enlightClass(m)===prog))return false;
    const borrowed=$('dtideBorrowed').value,hasBorrow=row.team.members.some(m=>m.borrowed);if(borrowed==='yes'&&!hasBorrow)return false;if(borrowed==='no'&&hasBorrow)return false;
    const wheel=$('dtideWheel').value,cov=$('dtideCovenant').value;if(wheel&&!targets.some(m=>(m.wheels||[]).some(x=>String(x.id??x.name)===wheel)))return false;if(cov&&!targets.some(m=>(m.covenants||((m.covenant)?[m.covenant]:[])).some(x=>String(x.id??x.name)===cov)))return false;
    const csmin=$('dtideCovenantScoreMin').value===''?null:Number($('dtideCovenantScoreMin').value),csmax=$('dtideCovenantScoreMax').value===''?null:Number($('dtideCovenantScoreMax').value);if(csmin!=null&&targets.some(m=>m.covenantScore==null||Number(m.covenantScore)<csmin))return false;if(csmax!=null&&targets.some(m=>m.covenantScore==null||Number(m.covenantScore)>csmax))return false;
    const smin=Number($('dtideScoreMin').value||0),rmax=Number($('dtideRankMax').value||0);if(smin&&(row.record.score||0)<smin)return false;if(rmax&&(!row.record.rank||row.record.rank>rmax))return false;return true;
  }
  function renderResults(){
    if(!$('dtideResults')||!$('dtidePager'))return;
    searchPerformed=true;
    const all=flattenTeams().filter(matchesFilters),limit=200,rows=all.slice(0,limit);$('dtideResults').innerHTML=rows.map(({record,wave,team,difficulty})=>`<article class="dtideResult"><div class="dtideResultHead"><b>#${esc(record.rank??'—')} ${esc(record.player)} · Wave ${wave.wave} · ${esc(difficultyZh[difficulty]||difficultyZh.unknown)} · ${team.clearType==='extra'?'Extra Clear':'Clear'} · ${esc(record.score??'—')} 分</b><a href="${esc(record.url)}" target="_blank" rel="noopener noreferrer">查看 Eremora 原记录</a></div><div class="dtideMembers">${team.members.map(m=>{const info=characterInfo(m.skeydbId||m.ingameId||memberKey(m),m),wn=(m.wheels||[]).map(wheelName).filter(Boolean).join(' / '),cn=(m.covenants||((m.covenant)?[m.covenant]:[])).map(x=>x.name).filter(Boolean).join(' / '),ec=enlightClass(m);return `<div class="dtideMember">${info.image?`<img class="dtideMemberAvatar" src="${esc(info.image)}" alt="" loading="lazy">`:''}<b>${esc(info.name||m.canonicalName||m.name)}</b><small>Lv.${esc(m.level??'—')} · ${esc(enlightZh[ec])}${m.covenantScore!=null?` · 密契评分 ${esc(m.covenantScore)}`:''}</small>${wn?`<small class="dtideGear">命轮：${esc(wn)}</small>`:''}${cn?`<small class="dtideGear">密契：${esc(cn)}</small>`:''}${m.borrowed?'<small class="dtideBorrow">借用助战</small>':''}</div>`}).join('')}</div></article>`).join('')||'<div class="dtideEmpty">没有符合这些条件的配队。</div>';$('dtidePager').textContent=`匹配 ${all.length} 支队伍${all.length>limit?` · 当前显示前 ${limit} 支`:''}`;
  }
  function renderSearchPrompt(){if(!$('dtideResults')||!$('dtidePager'))return;$('dtideResults').innerHTML='<div class="dtideEmpty">设置筛选条件后点击“搜索配队”查看结果。</div>';$('dtidePager').textContent=''}
  function resetFilters(){for(const id of ['dtideLevelMin','dtideLevelMax','dtideCovenantScoreMin','dtideCovenantScoreMax','dtideScoreMin','dtideRankMax'])$(id).value='';for(const id of ['dtideProgression','dtideBorrowed','dtideWheel','dtideCovenant'])$(id).value='';for(const id of ['dtideCharacters','dtideExcludeCharacters'])for(const o of $(id).options)o.selected=false;$('dtideCharacterMode').value='all';searchPerformed=false;renderSearchPrompt()}
  function renderAll(){renderSummary();renderMatrix();renderUsage();renderComparisons();if(filtersReady&&searchPerformed)renderResults();else if(filtersReady)renderSearchPrompt()}
  function relocalizeControls(){
    for(const id of ['dtideCharacters','dtideExcludeCharacters','dtideEquipCharacter'])for(const option of $(id)?.options||[]){if(!option.value)continue;option.textContent=characterInfo(option.value).name}
    const wheels=new Map();for(const {team} of flattenTeams())for(const member of team.members||[])for(const item of member.wheels||[])wheels.set(String(item.id??item.name),item);
    for(const option of $('dtideWheel')?.options||[]){if(!option.value)continue;const item=wheels.get(option.value);if(item)option.textContent=wheelName(item)}
    if(season)renderAll();
  }

  async function loadSeason(id){
    searchPerformed=false;$('dtideStatus').textContent='正在载入期次…';const entry=manifest.availableSeasons.find(x=>String(x.seasonId)===String(id));if(!entry)throw new Error(`Season ${id} snapshot unavailable`);const current=Number(id)===Number(manifest.currentSeason)&&manifest.usageIndex?.path?{path:manifest.usageIndex.path,statsPath:manifest.usageIndex.statsPath}:entry,revision=encodeURIComponent(manifest.usageIndex?.syncedAt||manifest.analytics?.generatedAt||manifest.source?.syncedAt||'1'),versioned=p=>{const u=new URL(p,document.baseURI);u.searchParams.set('v',revision);return u.href};const [sr,st]=await Promise.all([fetch(versioned(current.path),{cache:'force-cache'}),fetch(versioned(current.statsPath),{cache:'force-cache'})]);if(!sr.ok||!st.ok)throw new Error(`season HTTP ${sr.status}, stats HTTP ${st.status}`);const index=await sr.json();if(index.format==='gzip-base64-chunked-v1'){const parts=await Promise.all(index.chunks.map(async p=>{const r=await fetch(versioned(p),{cache:'force-cache'});if(!r.ok)throw new Error(`${p}: HTTP ${r.status}`);const bin=atob(await r.text()),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}));const total=parts.reduce((n,x)=>n+x.length,0),bytes=new Uint8Array(total);let off=0;for(const p of parts){bytes.set(p,off);off+=p.length}const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));season={...index,...JSON.parse(await new Response(stream).text())}}else season=Array.isArray(index.chunks)?{...index,records:(await Promise.all(index.chunks.map(p=>fetch(versioned(p),{cache:'force-cache'}).then(r=>r.json())))).flatMap(x=>x.records||[])}:index;stats=await st.json();const waves=[...new Set(flattenTeams().map(x=>Number(x.wave.wave)))].sort((a,b)=>a-b);$('dtideWave').innerHTML='<option value="all">全部波次</option>'+waves.map(w=>`<option value="${w}">Wave ${w}</option>`).join('');populateFilters();renderAll();
  }
  async function loadOnce(){
    if(manifest)return;try{await waitMorimensData();for(const r of window.MorimensData?.db?.records||[]){awakenerMap.set(r.id,r);if(r.ingameId)awakenerMap.set(r.ingameId,r)}const r=await fetch('data/morimens/eremora/manifest.json',{cache:'no-cache'});if(!r.ok)throw new Error(`manifest HTTP ${r.status}`);manifest=await r.json();const sel=$('dtideSeason');if(!sel)throw new Error('期次选择器尚未挂载');sel.innerHTML=(manifest.availableSeasons||[]).map(s=>`<option value="${s.seasonId}">第 ${s.seasonId} 期 · ${s.recordCount??0} 条${s.complete?' · 完整':' · 部分'}</option>`).join('');if(!sel.options.length)throw new Error('暂无融灾快照');sel.value=String(manifest.currentSeason&&manifest.availableSeasons.some(x=>x.seasonId===manifest.currentSeason)?manifest.currentSeason:manifest.availableSeasons[0].seasonId);await loadSeason(sel.value);const pending=manifest.pendingBackfillSeasonIds||[];const note=$('dtideCoverageNote');if(note)note.innerHTML=`<strong>字段真实性：</strong>${esc((manifest.notes||[]).join(' '))}${pending.length?` 当前 ${pending.length} 个历史期次仍为增量快照：${pending.slice(0,12).join('、')}${pending.length>12?'…':''}`:''}`;sel.addEventListener('change',()=>loadSeason(sel.value).catch(showError));for(const id of ['dtideRankScope','dtideDifficulty','dtideWave','dtideClearType','dtideRateMode','dtideSort'])$(id)?.addEventListener('change',renderAll);$('dtideEquipCharacter')?.addEventListener('change',renderEquipment);$('dtideSearch')?.addEventListener('click',renderResults);$('dtideReset')?.addEventListener('click',resetFilters);$('dtideUsage')?.addEventListener('click',e=>{const card=e.target.closest('[data-character-index]');if(!card)return;const c=currentGroup().characters[Number(card.dataset.characterIndex)];if(!c)return;document.querySelectorAll('.dtideInlineDetail').forEach(x=>x.remove());const block=(title,arr)=>'<h4>'+title+'</h4><div class="dtideUsageCards">'+((arr||[]).slice(0,5).map(x=>'<div class="dtideUsage"><div><b>'+esc(x.name||x.key)+'</b><small>'+x.count+' 次</small></div><strong>'+pct(x.ratePct||x.teamRatePct)+'</strong></div>').join('')||'<div class="dtideEmpty">暂无数据</div>')+'</div>';const detail=document.createElement('div');detail.className='dtideInlineDetail';detail.innerHTML=block('Top5 队友出场率',c.teammates)+block('命轮出场率',c.wheels)+block('密契出场率',c.covenants);card.insertAdjacentElement('afterend',detail);card.setAttribute('aria-expanded','true')})}catch(e){showError(e)}
  }
  function showError(e){console.warn('D-Zone analytics failed',e);if($('dtideStatus'))$('dtideStatus').textContent='融灾数据加载失败';if($('dtideResults'))$('dtideResults').innerHTML=`<div class="dtideNotice">${esc(e?.message||e)}</div>`}
  function boot(){injectStyle();setupTabs();window.addEventListener('morimens-language-change',()=>{if($('morimensBuilderTab')){$('morimensBuilderTab').textContent=zh()?'伤害计算 / 每日签':'Damage / Fortune';$('morimensDtideTab').textContent=zh()?'融灾榜单':'D-Zone Leaderboard'}relocalizeControls()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();

